In [1]:
import numpy as np

### Ques 1. Write a function so that the columns of the output matrix are powers of the input vector.

### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [55]:
## Below function will execute exactly like inbuilt 'vander' function which exists in 'numpy' module.
## Just like existing 'vander' function, 'N' and 'increasing' parameters are 'None' and 'False' respectively. And if 'N' is None, then N=len(np_arr).
def vander(np_arr, N= None, increasing= False):
    n = len(np_arr)
    if N is None:
        N= n
    final_np_arr = np.empty((0, N), dtype= 'int')
    
    for i in range(n):
        a = list()
        for j in range(N):
            if increasing:
             a.append(np_arr[i] ** (j))
            else:
                a.append(np_arr[i] ** (N - j - 1))
        final_np_arr = np.append(final_np_arr, np.array([a]), axis = 0)
        
    return final_np_arr

In [56]:
vander([1, 2, 3, 5, 7])

array([[   1,    1,    1,    1,    1],
       [  16,    8,    4,    2,    1],
       [  81,   27,    9,    3,    1],
       [ 625,  125,   25,    5,    1],
       [2401,  343,   49,    7,    1]])

In [57]:
vander([1, 2, 3, 5, 7], 3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1],
       [49,  7,  1]])

In [58]:
vander([1, 2, 3, 5, 7], increasing= True)

array([[   1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16],
       [   1,    3,    9,   27,   81],
       [   1,    5,   25,  125,  625],
       [   1,    7,   49,  343, 2401]])

In [59]:
vander([1, 2, 3, 5, 7], N= 4, increasing= True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125],
       [  1,   7,  49, 343]])

#### Alternate way for Question 1. Directly applying 'vander' method of numpy.

In [61]:
def vander_apply(arr, N, increasing):
    return np.vander(arr, N, increasing)

vander_apply([1, 2, 3, 5, 7], 4, True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125],
       [  1,   7,  49, 343]])

### Ques 2. Write a function to find moving average in an array over a window:

### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [83]:
def mov_avg(arr, window):
    if window <= 0 or len(arr) <= window:
        return np.array([])
    if window == 1:
        return np.array(arr)
    
    res_arr = np.array([])
    
    for i in range(window - 1, len(arr)):
        res_arr = np.append(res_arr, [sum(arr[i - window + 1 : i + 1]) / window])
        
    return res_arr

In [84]:
mov_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [85]:
len(mov_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3))

11